"""Write the TUFLOW model: folder structure, control files and GIS layers.

Generated structure (TUFLOW conventions):

    <output_dir>/
      runs/                 .tcf, .tef, run log folder
      model/                .tgc, .tbc, materials.csv
      model/gis/            2d_code, 2d_loc, 2d_mat (PRE/POST), 2d_rf, 2d_bc, 2d_po, QA layers
      model/grid/           (DEM to be supplied by the modeller)
      bc_dbase/             bc_dbase.csv + rainfall/*.csv
      check/  results/      TUFLOW outputs
      <model_id>_run_all.bat
"""

from __future__ import annotations

from pathlib import Path

import geopandas as gpd
import pandas as pd
from shapely.geometry import LineString, Point, box

from .catchments import scenario_summary
from .config import BuildConfig
from .rainfall import aep_event_name, duration_event_name

GENERATED_NOTE = ("Generated by NZ TUFLOW Flood Model Builder - review all files, "
                  "the DEM reference and boundary locations before running.")


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def _folders(root: Path) -> dict[str, Path]:
    f = {
        "root": root,
        "runs": root / "runs",
        "runs_log": root / "runs" / "log",
        "model": root / "model",
        "gis": root / "model" / "gis",
        "grid": root / "model" / "grid",
        "bc": root / "bc_dbase",
        "rainfall": root / "bc_dbase" / "rainfall",
        "check": root / "check",
        "results": root / "results",
        "report": root / "report",
    }
    for p in f.values():
        p.mkdir(parents=True, exist_ok=True)
    return f


def _write_gis(gdf: gpd.GeoDataFrame, folder: Path, name: str, cfg: BuildConfig) -> str:
    """Write a GIS layer in the configured format; return the file name."""
    gdf = gdf.set_crs(epsg=cfg.epsg, allow_override=True)
    if cfg.gis_format == "shp":
        fn = f"{name}.shp"
        gdf.to_file(folder / fn)
    else:
        fn = f"{name}.gpkg"
        gdf.to_file(folder / fn, layer=name, driver="GPKG")
    return fn


def _domain(pre: gpd.GeoDataFrame, post: gpd.GeoDataFrame, cfg: BuildConfig):
    """Active-area polygon = buffered union of both scenarios' catchments."""
    union = pd.concat([pre.geometry, post.geometry], ignore_index=True).union_all()
    return union.buffer(cfg.grid_buffer)


# ---------------------------------------------------------------------------
# GIS layers
# ---------------------------------------------------------------------------

def write_gis_layers(pre: gpd.GeoDataFrame, post: gpd.GeoDataFrame,
                     cfg: BuildConfig, gis_dir: Path) -> dict[str, str]:
    files: dict[str, str] = {}
    mid = cfg.model_id
    domain = _domain(pre, post, cfg)
    minx, miny, maxx, maxy = domain.bounds

    # 2d_mat — material polygons per scenario (attribute 1 must be Material)
    for label, gdf in (("PRE", pre), ("POST", post)):
        mat = gdf[["material", "geometry"]].rename(columns={"material": "Material"})
        files[f"mat_{label}"] = _write_gis(mat, gis_dir, f"2d_mat_{mid}_{label}_001", cfg)
        # QA copy with full attribution for checking the auto-assignment
        qa = gdf.drop(columns=["scenario"], errors="ignore")
        files[f"qa_{label}"] = _write_gis(qa, gis_dir, f"0_qa_catchments_{label}", cfg)

    # 2d_code — active area (Code = 1)
    code = gpd.GeoDataFrame({"Code": [1]}, geometry=[domain], crs=f"EPSG:{cfg.epsg}")
    files["code"] = _write_gis(code, gis_dir, f"2d_code_{mid}_001", cfg)

    # 2d_loc — grid origin/orientation line along the SW edge of the domain
    loc = gpd.GeoDataFrame({"Comment": ["origin at first vertex, x-axis along line"]},
                           geometry=[LineString([(minx, miny), (maxx, miny)])],
                           crs=f"EPSG:{cfg.epsg}")
    files["loc"] = _write_gis(loc, gis_dir, f"2d_loc_{mid}_001", cfg)

    # 2d_rf — rainfall polygon over the active area (rain-on-grid)
    rf = gpd.GeoDataFrame({"Name": ["RF01"], "f1": [1.0], "f2": [1.0]},
                          geometry=[domain], crs=f"EPSG:{cfg.epsg}")
    files["rf"] = _write_gis(rf, gis_dir, f"2d_rf_{mid}_001", cfg)

    # 2d_bc — placeholder HQ (normal-depth) outlet along the downstream edge.
    # PLACE THIS LINE AT THE TRUE DOWNSTREAM BOUNDARY BEFORE RUNNING.
    bc_line = LineString([(minx + (maxx - minx) * 0.25, miny),
                          (minx + (maxx - minx) * 0.75, miny)])
    bc = gpd.GeoDataFrame(
        {"Type": ["HQ"], "Flags": [""], "Name": ["DS_OUT"], "f": [0.0],
         "d": [0.0], "td": [0.0], "a": [0.0], "b": [0.01]},
        geometry=[bc_line], crs=f"EPSG:{cfg.epsg}")
    files["bc"] = _write_gis(bc, gis_dir, f"2d_bc_{mid}_001", cfg)

    # 2d_po — reporting: water-level point at each catchment centroid (post
    # names preferred) and a template flow line just inside the outlet.
    pts, labels = [], []
    seen = set()
    for _, row in pd.concat([post, pre], ignore_index=True).iterrows():
        lbl = f"H_{_safe_label(row['catch_name'])}"
        if lbl in seen:
            continue
        seen.add(lbl)
        pts.append(row.geometry.representative_point())
        labels.append(lbl)
    po_pts = gpd.GeoDataFrame({"Type": ["H_"] * len(pts), "Label": labels},
                              geometry=pts, crs=f"EPSG:{cfg.epsg}")
    files["po_points"] = _write_gis(po_pts, gis_dir, f"2d_po_{mid}_P_001", cfg)

    q_line = LineString([(minx + (maxx - minx) * 0.25, miny + cfg.cell_size * 3),
                         (minx + (maxx - minx) * 0.75, miny + cfg.cell_size * 3)])
    po_ln = gpd.GeoDataFrame({"Type": ["Q_"], "Label": ["Q_OUTLET"]},
                             geometry=[q_line], crs=f"EPSG:{cfg.epsg}")
    files["po_lines"] = _write_gis(po_ln, gis_dir, f"2d_po_{mid}_L_001", cfg)

    files["_grid"] = {
        "nx": int((maxx - minx) // cfg.cell_size + 1),
        "ny": int((maxy - miny) // cfg.cell_size + 1),
        "size_x": round(maxx - minx, 1),
        "size_y": round(maxy - miny, 1),
    }
    return files


def _safe_label(name: str) -> str:
    return "".join(c if c.isalnum() else "_" for c in str(name)).strip("_")[:40]


# ---------------------------------------------------------------------------
# Control files
# ---------------------------------------------------------------------------

def materials_csv(cfg: BuildConfig) -> str:
    lines = [
        "! materials.csv - " + GENERATED_NOTE,
        "! Losses are rainfall-on-grid losses (IL mm, CL mm/hr). Review against the",
        "! relevant council modelling specification before use.",
        "Material ID,Manning's n,\"Rainfall Losses (IL mm, CL mm/hr)\",Land Use Hazard ID,SRF,Fraction Impervious,!Description",
    ]
    for m in cfg.materials:
        lines.append(
            f"{m.id},{m.n:.3f},\"{m.il:g}, {m.cl:g}\",,0,{m.imperv:.2f},! {m.name}")
    return "\n".join(lines) + "\n"


def bc_dbase_csv() -> str:
    return (
        "Name,Source,Column 1,Column 2,Add Col 1,Mult Col 2,Add Col 2,Column 3,Column 4\n"
        "RF01,rainfall\\rf_~AEP~_~DUR~_~CC~.csv,Time_hr,Rain_mm,,,,,\n"
    )


def tgc_text(cfg: BuildConfig, files: dict, grid: dict) -> str:
    mid = cfg.model_id
    return f"""! TUFLOW Geometry Control File - {cfg.project_name}
! {GENERATED_NOTE}

Cell Size == {cfg.cell_size:g}
Read GIS Location == gis\\{files['loc']}
Grid Size (X,Y) == {grid['size_x']:g}, {grid['size_y']:g}

Set Code == 0
Read GIS Code == gis\\{files['code']}

! --- Elevations: supply the project DEM (LiDAR-derived) here ---
Read GRID Zpts == {cfg.dem_path}

! --- Land use / roughness (auto-assigned from catchment names) ---
Set Mat == {cfg.fallback_material_id}
If Scenario == PRE
    Read GIS Mat == gis\\{files['mat_PRE']}
Else If Scenario == POST
    Read GIS Mat == gis\\{files['mat_POST']}
Else
    Pause == Unknown scenario - use -s1 PRE or -s1 POST
End If
"""


def tbc_text(cfg: BuildConfig, files: dict) -> str:
    return f"""! TUFLOW Boundary Conditions Control File - {cfg.project_name}
! {GENERATED_NOTE}

! Direct rainfall over the active area (hyetographs in bc_dbase\\rainfall)
Read GIS RF == gis\\{files['rf']}

! Downstream boundary - HQ (normal depth) line, slope in attribute 'b'.
! *** The generated line is a placeholder along the southern edge of the   ***
! *** domain. Move it to the true downstream boundary before running.      ***
Read GIS BC == gis\\{files['bc']}
"""


def tef_text(cfg: BuildConfig) -> str:
    lines = [f"! TUFLOW Event File - {cfg.project_name}",
             f"! {GENERATED_NOTE}", ""]
    lines.append("! --- e1: Annual Exceedance Probability ---")
    for aep in cfg.aeps:
        name = aep_event_name(aep)
        lines += [f"Define Event == {name}",
                  f"    BC Event Source == ~AEP~ | {name}",
                  "End Define", ""]
    lines.append("! --- e2: storm duration (sets simulation end time) ---")
    for dur in cfg.storm_durations_hr:
        name = duration_event_name(dur)
        end_t = dur + cfg.run_time_buffer_hr
        lines += [f"Define Event == {name}",
                  f"    BC Event Source == ~DUR~ | {name}",
                  f"    End Time == {end_t:g}",
                  "End Define", ""]
    lines.append("! --- e3: climate change scenario ---")
    for cc in cfg.cc_scenarios:
        lines += [f"Define Event == {cc.name}",
                  f"    BC Event Source == ~CC~ | {cc.name}",
                  "End Define", ""]
    return "\n".join(lines)


def tcf_text(cfg: BuildConfig, files: dict) -> str:
    mid = cfg.model_id
    ts = cfg.timestep_2d if cfg.timestep_2d else cfg.cell_size / 2.0
    hardware = "GPU" if cfg.hardware_gpu else "CPU"
    gpkg_proj = (f"GPKG Projection == ..\\model\\gis\\{files['code']}"
                 if cfg.gis_format == "gpkg"
                 else f"SHP Projection == ..\\model\\gis\\{Path(files['code']).stem}.prj")
    return f"""! TUFLOW Control File - {cfg.project_name} ({mid})
! {GENERATED_NOTE}
!
! Scenarios: -s1 PRE | POST
! Events:    -e1 AEP (e.g. {aep_event_name(cfg.aeps[-1])})  -e2 duration (e.g. {duration_event_name(cfg.storm_durations_hr[-1])})  -e3 climate ({', '.join(c.name for c in cfg.cc_scenarios)})

GIS Format == {cfg.gis_format.upper()}
{gpkg_proj}
TUFLOW Units == Metric

Solution Scheme == HPC
Hardware == {hardware}
SGS == ON
SGS Sample Target Distance == {max(cfg.cell_size / 4.0, 0.5):g}

Event File == {mid}_events.tef
BC Database == ..\\bc_dbase\\bc_dbase.csv
Read Materials File == ..\\model\\materials.csv

Geometry Control File == ..\\model\\{mid}_001.tgc
BC Control File == ..\\model\\{mid}_001.tbc

Set IWL == 0.0
Start Time == 0
Timestep == {ts:g}
! End Time is set per duration event in the .tef

! --- Outputs ---
Log Folder == log
Output Folder == ..\\results\\
Write Check Files == ..\\check\\
Map Output Format == XMDF TIF
Map Output Data Types == h d V q
Map Output Interval == {cfg.output_interval_s:g}
TIF Map Output Data Types == h d V Z0
TIF Map Output Interval == 0   ! maximums only

! --- Reporting (plot outputs) ---
Read GIS PO == ..\\model\\gis\\{files['po_points']}
Read GIS PO == ..\\model\\gis\\{files['po_lines']}
Time Series Output Interval == 60
"""


def batch_text(cfg: BuildConfig) -> str:
    mid = cfg.model_id
    aeps = " ".join(aep_event_name(a) for a in cfg.aeps)
    durs = " ".join(duration_event_name(d) for d in cfg.storm_durations_hr)
    ccs = " ".join(c.name for c in cfg.cc_scenarios)
    return f"""@echo off
rem Run all scenario/event combinations - {cfg.project_name}
rem {GENERATED_NOTE}
rem Update the TUFLOW executable path below.
set TUFLOW=C:\\TUFLOW\\Releases\\2025.1\\TUFLOW_iSP_w64.exe

for %%S in (PRE POST) do (
  for %%A in ({aeps}) do (
    for %%D in ({durs}) do (
      for %%C in ({ccs}) do (
        "%TUFLOW%" -b -s1 %%S -e1 %%A -e2 %%D -e3 %%C "runs\\{mid}_~s1~_~e1~_~e2~_~e3~_001.tcf"
      )
    )
  )
)
"""


# ---------------------------------------------------------------------------
# Top level build
# ---------------------------------------------------------------------------

def build_model(cfg: BuildConfig, pre: gpd.GeoDataFrame, post: gpd.GeoDataFrame,
                storms: dict[tuple[str, str, str], pd.DataFrame],
                out_dir: str | Path | None = None) -> dict:
    """Write the complete TUFLOW model. Returns a manifest of written files."""
    root = Path(out_dir or cfg.output_dir)
    f = _folders(root)
    mid = cfg.model_id

    gis_files = write_gis_layers(pre, post, cfg, f["gis"])
    grid = gis_files.pop("_grid")

    (f["model"] / "materials.csv").write_text(materials_csv(cfg), encoding="utf-8")
    (f["model"] / f"{mid}_001.tgc").write_text(tgc_text(cfg, gis_files, grid), encoding="utf-8")
    (f["model"] / f"{mid}_001.tbc").write_text(tbc_text(cfg, gis_files), encoding="utf-8")
    (f["bc"] / "bc_dbase.csv").write_text(bc_dbase_csv(), encoding="utf-8")

    for (aep, dur, cc), df in storms.items():
        df.to_csv(f["rainfall"] / f"rf_{aep}_{dur}_{cc}.csv", index=False)

    tcf_name = f"{mid}_~s1~_~e1~_~e2~_~e3~_001.tcf"
    (f["runs"] / tcf_name).write_text(tcf_text(cfg, gis_files), encoding="utf-8")
    (f["runs"] / f"{mid}_events.tef").write_text(tef_text(cfg), encoding="utf-8")
    (root / f"{mid}_run_all.bat").write_text(batch_text(cfg), encoding="utf-8")

    # summary CSVs for reporting
    scenario_summary(pre).to_csv(f["report"] / "landuse_summary_PRE.csv", index=False)
    scenario_summary(post).to_csv(f["report"] / "landuse_summary_POST.csv", index=False)

    cfg.to_yaml(root / "build_config.yaml")

    n_runs = 2 * len(cfg.aeps) * len(cfg.storm_durations_hr) * len(cfg.cc_scenarios)
    return {
        "root": str(root),
        "tcf": str(f["runs"] / tcf_name),
        "gis_files": gis_files,
        "grid": grid,
        "n_rainfall_files": len(storms),
        "n_runs": n_runs,
    }
